version: '3.2'

services:
  kafka1:
    image: jasonlift/rpi-kafka
    restart: always
    ports:
    - "9094:9094"
    - "9992:9992"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.249.77.186:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: 10.249.77.186:2181,10.249.77.188:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pinet

  kafka2:
    image: jasonlift/rpi-kafka
    restart: always
    ports:
    - "9094:9094"
    - "9992:9992"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.249.77.188:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: 10.249.77.186:2181,10.249.77.188:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pinet

networks:
  pinet:
    external:
      name: pi-network